### PR TITLE
Added license file for 0BSD

### PR DESCRIPTION
**Pull request by jhabdas**
Hey Nazar sweet looking date picker! [Dark UIs](https://after-dark.habd.as) are my favorite.

I'm working on getting the OBSD license added to choosealicense.com now that OSI [has officially renamed](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2018-November/003830.html) the FPL 1.0.0 to "Zero-Clause BSD".

Your library [was suggested](https://github.com/github/choosealicense.com/issues/642#issuecomment-463129064) as one of the more popular ones on GitHub using 0BSD so I've prepared this pull request to help satisfy the conditions necessary for a license to be listed on that website. I used a lowercase filename with a `txt` file extension to match your other files—hope that's okay and you don't mind adding this to your site either via merge or in a separate commit.

### CODE REVIEW

**Comment by waldyrious** [comment]
@jhabdas just for the sake of recognizability, I'd add the license title at the top (as is already customary with MIT, etc.)

**Comment by nazar-pc** [comment]
The idea behind changing license of multiple libraries and tools I develop to 0BSD was to:
1) Remove words "copyright", since it is literally not applicable in case of 0BSD and I'm not going to start litigation against anyone on license violation anyway
2) Stop changing year in typical copyright notice in every file every year

Hence I'm reluctant to accept this PR as is.

I'll accept PR is you don't mind removing copyright line from license file and correcting readme to:
1) Remove mention of Free Public License 1.0.0
2) Correct link to 0BSD

**Comment by nazar-pc** [comment]
Also I like word "license" not much more than "copyright", that was why I removed license file a while ago entirely, but I'm fine bringing it back.

**Comment by jhabdas** [comment]
@nazar-pc Removed copyright line and updated readme. I'm also not a fan of the word "license" so I've renamed the file to `copying.md` to preserve gnu vestiges and align the file extension with your other plain text files.

@waldyrious I brought up your idea [here](https://github.com/spdx/license-list/issues/23#issuecomment-463467132) but as it stands license title is not part of the license text.

**Comment by nazar-pc** [comment]
Nice, happy to see GitHub supports copying.md file

**Comment by jhabdas** [comment]
Thanks!

**Comment by waldyrious** [comment]
> as it stands license title is not part of the license text.

@jhabdas IIUC licenses like MIT also don't require the title to be legally valid -- MIT, in particular, says:

> the above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.

In any case, adding the title has no legal consequence, since the entire license text is still present (tools like [licensee](https://github.com/benbalter/licensee) are indeed quite permissive in that regard precisely because of this). Since the title does make the license file more human-friendly (and helps disseminating the license), I'd still advocate for its inclusion.

**Pull request merged**
