### PR TITLE
Fix for missing styles on Twitter Bootstrap

### LINKED ISSUE #73: Twitter Bootstrap Integration не работает в Google Chrome
Не работает выделение и подсветка. Насколько я понял проблема где-то здесь:
      panel = $('&lt;div class="panel" />');
      button = $('&lt;button class="btn btn-default" />');
      link_hover = $('&lt;button class="btn btn-link" />').hover();
      text_muted = $('&lt;span class="text-muted" />');
      disabled = $('&lt;span class="text-muted" />');
      selected = $('&lt;div class="alert alert-info" />');
      parameters = {
        $border_radius: '.4em',
        $background: panel.css('background-color'),

Google Chrome не может получить значение стиля у $('&lt;div class="panel" />') в panel.css('background-color') и далее по коду.

Пример получения значения стиля: http://fiddle.jshell.net/aa42p0o7/3/ - работает в Firefox'е, но не работает в Crome'е.

### PR DESCRIPTION
**Pull request by EHLOVader**
May have only affected Chrome but without the elements placed in the DOM css would not return calculated styles.
To fix this I force them into the dom through a hidden div which is later removed.

Open to suggestions if there is a better way. I tried to limit the redraws by only pushing to the dom once for all six elements.

Fixes #73

### CODE REVIEW

**Comment by EHLOVader** [comment]
Sorry had forgotten the append I missed it in a copy paste incident locally. Testing if it works like it should. Will have a fiddle to share shortly.

**Comment by nazar-pc** [comment]
Looks like nothing changed in Firefox: https://jsfiddle.net/ukbpy674/10/
I remember I've tried, it should work even on disconnected items, other styles work fine as you can see, we're just picking colors from wrong element.

**Comment by EHLOVader** [comment]
I have it working locally..

local bootstrap with diff colors

**Comment by nazar-pc** [comment]
Well, can you make fsfiddle for that?

**Comment by EHLOVader** [comment]
Yup!!!1 

That is what I was trying to do. Still couldn't reproduce what I did locally first off. but played around with the scripts a bit. Using different methods to append and remove etc etc...

https://jsfiddle.net/ngnykw3n/

**Comment by EHLOVader** [comment]
Something is still not right.. trying a few things to make sure the copy in my PR works. Not sure why it would be different. The use of the selector shouldn't make a difference.

**Comment by nazar-pc** [comment]
1) Once again, in this case you don't need `pickmeup.css`, it may cause some problems
2) I'd use `<div hidden></div>` instead of `<div class="hide"></div>`, it is supported by all major browsers now
3)  Please, apply the same tweak to UIkit integration, code is completely similar there

**Comment by nazar-pc** [comment]
@elkernos, is it working for you?

**Comment by EHLOVader** [comment]
It doesn't seem to be that stylesheet. 

I can get it working "inline" with it in the javascript box. but not as an external resource.

**Comment by EHLOVader** [comment]
Before I get into UIkit... and any other problems I wanted to know... without a `contributing.md` did I make the compiled coffeescript and minified files correctly?

```
coffee --compile js/jquery.pickmeup.twitter-bootstrap.coffee
uglifyjs js/jquery.pickmeup.twitter-bootstrap.js --comments --output js/jquery.pickmeup.twitter-bootstrap.min.js
```

**Comment by nazar-pc** [comment]
I'm compiling it automatically in PhpStorm using File Watchers, also there is minifier in context menu in IDE.
I think what you use is fine.

**Comment by EHLOVader** [comment]
Perfect. I tried that in PHPStorm but it didn't want to work. So I jumped into the shell for a fix. 

Admittedly I don't work with coffeescript normally. So I wanted to check. 

Since nothing seems to be working for me tonight, I am going to give it some thought and re approach it tomorrow.

**Comment by nazar-pc** [comment]
Should be fixed in 4ff48a5

**Pull request closed without merging**
