### PR TITLE
Feature: method to change an element relative to which the datepicker is rendered

### PR DESCRIPTION
**Pull request by knitevision1**
Not sure who will ever need this functionality, well, I needed for some reason.
This allows to show/hide more smoothly and numerous places to hang the plugin on the page.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Looks like you're only showing it relatively to some element, but actual position in DOM doesn't change form that.
What is the reason that you can't instantiate PickMeUp on `attach_to` initially? Would be useful to know more about your use case.

**Comment by knitevision1** [comment]
@nazar-pc 
Well I just needed a quick and reliable way to show the calendar in another place, rather than close to the element that triggers it's appearance.

Using CSS class - not good enough.
Attach a datepicker and then use `.show / .hide` methods on event - too.

So I came up with this. Yes, position in the DOM doesn't change (didn't mean to do that), but an element, relative to which the calendar is rendered, changes, which can be helpful in some cases.

Maybe setting option should be renamed to `relative_to`

**Comment by nazar-pc** [comment]
I'd rather like to see something generic responsible for positioning. I mean, so that you can replace default positioning algorithm with your own (because built-in is pretty simple). It was actually already requested in #111. In your case, however, I'd better use events handlers to combine datepicker in one place and input in another place (in this case you'll be able to use upstream version and upgrade to newer releases).

So it would be nice if you can implement something more generic (I imaging `position` event) for this use case, rather than in a way it is currently. There are too many edge cases, I can't support all of them.

**Comment by Supermanaco** [comment]
Hallo nazar-pc,
thanks for your really good calendar-tool. I have a problem. Maybe you could help me. In my form are many input fields. And now it doesnt work. How can I solve this with a class? Thx for your help.

**Comment by nazar-pc** [comment]
@Supermanaco
1) Don't spam in irrelevant issues/pull requests (create new issue instead)
2) More details needed (or demo, which is even better)

**Comment by nazar-pc** [comment]
I've just published 3.1.0 that supports custom function in `position` option, so now it is possible to implement arbitrary positioning in generic way and this PR is not needed

**Pull request closed without merging**
