### PR TITLE
Added UMD support

### PR DESCRIPTION
**Pull request by przemyslaw-piatek**
Added UMD support to the plugin, so it can be also loaded as AMD or CommonJS module.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Awesome, thanks a lot!

**Comment by przemyslaw-piatek** [comment]
You're welcome. Any estimates on releasing a version with this enhancement?

**Comment by nazar-pc** [comment]
Up to an hour I guess, just preparing release notes for another project https://github.com/nazar-pc/CleverStyle-CMS

**Comment by przemyslaw-piatek** [comment]
Brilliant, cheers!

**Comment by nazar-pc** [comment]
https://github.com/nazar-pc/PickMeUp/releases/tag/2.7.0

**Pull request merged**
